export const CONNECT = 'connect';
export const DISCONNECT = 'disconnect';
export const HONEYPOT_SERVICE = 'start';
export const ERROR = 'error';
export const MESSAGE = 'message';
export const RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const HONEYPOT_EXECUTION_STATE_UPDATE = 'HONEYPOT_EXECUTION_STATE_UPDATE';
export const HONEYPOT_CHANGE_STATE_UPDATE = 'HONEYPOT_CHANGE_STATE_UPDATE';
export const FETCH_NEW_SNAPSHOT_DETAILS = 'FETCH_NEW_SNAPSHOT_DETAILS';
export const REMOVE_HONEYPOT_FROM_STATE = 'REMOVE_HONEYPOT_FROM_STATE';
export const FAIL_STATE_OF_HONEYPOT = 'FAIL_STATE_OF_HONEYPOT';
export const UPDATE_FOR_SNAPSHOT_DOWNLOAD = 'UPDATE_FOR_SNAPSHOT_DOWNLOAD';
export const FILE_UPLOAD_STATE_CHANGE = 'FILE_UPLOAD_STATE_CHANGE';
export const DASHBOARD_ATTACKER_UPDATE = 'DASHBOARD_ATTACKER_UPDATE';
export const DASHBOARD_TIMELINE_UPDATE = 'DASHBOARD_TIMELINE_UPDATE';
export const DASHBOARD_TOP_HONEYPOTS = 'DASHBOARD_TOP_HONEYPOTS';
export const DASHBOARD_HONEYPOT_PORT_DIST = 'DASHBOARD_HONEYPOT_PORT_DIST';
export const DASHBOARD_RECENT_LOGS = 'DASHBOARD_RECENT_LOGS';
export const DASHBOARD_RECENT_CREDS = 'DASHBOARD_RECENT_CREDS';

/**
 * AD events
 */
export const AD_EXECUTION_STATE_UPDATE = 'AD_EXECUTION_STATE_UPDATE';
export const AD_FILE_UPLOADED = 'AD_FILE_UPLOADED';
export const FAIL_STATE_OF_AD = 'FAIL_STATE_OF_AD';
export const REMOVE_ADCHILD_FROM_STATE = 'REMOVE_ADCHILD_FROM_STATE';

/**
 * Token Events
 */
export const DOWNLOAD_HONEYTOKEN = 'DOWNLOAD_HONEYTOKEN';
export const INSERT_TOKEN_TRIGGER = 'INSERT_TOKEN_TRIGGER';
export const INJECT_BROWSER_CREDENTIAL = 'INJECT_BROWSER_CREDENTIAL';
export const CREATE_FOLDER_HONEYTOKEN = 'CREATE_FOLDER_HONEYTOKEN';
export const SET_COMMAND_MONITOR_TOKEN = 'SET_COMMAND_MONITOR_TOKEN';
export const INJECT_FAKE_RESPONSE = 'INJECT_FAKE_RESPONSE';
export const PROTECT_DIRECTORY = 'PROTECT_DIRECTORY';
export const GET_EVENTS = 'GET_EVENTS';
export const ADD_NETWORK_LEVEL = 'ADD_NETWORK_LEVEL';
export const DELETE_NETWORK_LEVEL = 'DELETE_NETWORK_LEVEL';
export const INSERT_EVENT_TRIGGER = 'INSERT_EVENT_TRIGGER';
export const DELETE_MINE = 'DELETE_MINE';
export const DELETE_COMMAND_MINE = 'DELETE_COMMAND_MINE';
export const GET_FAKE_RESPONSES = 'GET_FAKE_RESPONSES';
export const DELETE_FAKE_RESPONSE = 'DELETE_FAKE_RESPONSE';
export const VALHALA = 'VALHALA';
